version: "3.7"

networks: 
  nifi_network:


services: 

  nifi-registry:
    image: apache/nifi-registry:1.14.0
    container_name: nifi-registry
    environment: 
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
    volumes: 
      - ./database:/opt/nifi-registry/nifi-registry-current/database
      - ./flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    ports: 
      - 18080:18080
    user: '1000:0'
    networks: 
      - nifi_network

  nifi:
    image: apache/nifi:1.14.0
    container_name: nifi
    environment: 
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes: 
      - ./json-files-sample:/home/nifi/json-files-sample
      - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./content_repository:/opt/nifi/nifi-current/content_repository
      - ./database_repository:/opt/nifi/nifi-current/database_repository
    ports: 
     - 8443:8443
    depends_on: 
      - nifi-registry
    user: '1000:1000'
    networks:
      - nifi_network
