version: "3.7"

x-node-environment: &node-environment
  - NIFI_WEB_HTTP_PORT=8080
  - NIFI_CLUSTER_IS_NODE=true
  - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
  - NIFI_ZK_CONNECT_STRING=zookeeper:2181
  - NIFI_ELECTION_MAX_WAIT=1 min
  - NIFI_SENSITIVE_PROPS_KEY=1NJDAdi3hu3j


networks:
  nifi_network:


services:

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181 
    volumes:
      - ./zookeeper-data/data:/data
      - ./zookeeper-data/datalog:/datalog
      - ./zookeeper-data/logs:/logs
    ports: 
      - 2181:2181
    networks:
      - nifi_network

  nifi-registry:
    image: apache/nifi-registry:1.14.0
    container_name: nifi-registry
    networks:
      - nifi_network
    hostname: nifi-registry
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
    volumes:
      - ./registry-data/database:/opt/nifi-registry/nifi-registry-current/database
      - ./registry-data/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    ports:
      - 18080:18080
    user: '1000:0'

  nifi-0:
    image: apache/nifi:1.14.0
    container_name: nifi-0
    networks:
      - nifi_network
    user: '1000:1000'
    hostname: nifi-0
    environment:
      *node-environment
    volumes:
      - ./json-files-sample:/home/nifi/json-files-sample
      - ./nifi-data-0/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi-data-0/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi-data-0/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi-data-0/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi-data-0/state:/opt/nifi/nifi-current/state
    ports:
     - 8080:8080
    depends_on:
      - zookeeper
      - nifi-registry

  nifi-1:
    image: apache/nifi:1.14.0
    container_name: nifi-1
    networks:
      - nifi_network
    user: '1000:1000'
    hostname: nifi-1
    environment:
      *node-environment
    ports:
     - 8081:8080
    depends_on:
      - zookeeper
      - nifi-registry

  nifi-2:
    image: apache/nifi:1.14.0
    container_name: nifi-2
    networks:
      - nifi_network
    user: '1000:1000'
    hostname: nifi-2
    environment:
      *node-environment
    ports:
     - 8082:8080
    depends_on:
      - zookeeper
      - nifi-registry
